
project_id = "iympksahhwfpirxtoljs"

[functions.track-registration]
verify_jwt = false

[functions.ai-query]
verify_jwt = false

[functions.chat-with-ai]
verify_jwt = false

[functions.check-table-exists]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.track-query]
verify_jwt = false

[functions.update-profile]
verify_jwt = true
