
# This is a config file for the Supabase CLI

project_id = "iympksahhwfpirxtoljs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[functions]
serve_port = 54324
```
