// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iympksahhwfpirxtoljs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5bXBrc2FoaHdmcGlyeHRvbGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTM4NzksImV4cCI6MjA2MTIyOTg3OX0.-cNhRxmkcpnoor42GieeKhuHwYWUqTCBqWCxDjwcpAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);